// This file has been autogenerated from a class added in the UI designer.
using System;
using Foundation;
using UIKit;
using SharedCode.Model.DB;
using SharedCode.Controller;
using SharedCode.Services;
using System.Linq;
using SharedCode.Util;
using SharedCode.Model.Api;
using FFImageLoading;

namespace PokeAppiOS.Views
{
	public partial class PokemonBaseInfoViewController : UIViewController
	{
        IPokemonDetailController controller = IocContainer.GetDependency<IPokemonDetailController>();
        public PokemonLocal Pokemon;
		private UIColor _primaryColor;

		public PokemonBaseInfoViewController (IntPtr handle) : base (handle)
		{
		}

		public async void UpdateInfo()
		{
			if (Pokemon == null) return;
			var primaryType = Pokemon.TypesArray.FirstOrDefault();
			_primaryColor = UIColor.FromName(primaryType);
            ImageLoaderService.LoadImageFromUrl(Pokemon.ShinySprite)
                .Error(ex =>
                {
                    Console.Write(ex);
                })
                .Into(shinyImageView);
            happinessValueLabel.Text = Pokemon.BaseHappiness.ToString();
			happinessValueLabel.TextColor = _primaryColor;

			habitadValueLabel.Text = StringUtils.ToTitleCase(Pokemon.Habitat ?? "No Habitat");
			habitadValueLabel.TextColor = _primaryColor;

			generationValueLabel.Text = Pokemon.GetGenerationRomanNumeral();
			generationValueLabel.TextColor = _primaryColor;

			regionNameLabel.Text = StringUtils.ToTitleCase(Pokemon.Region ?? "No Region");
			regionNameLabel.TextColor = _primaryColor;

			descriptionLabel.Text = Pokemon.FlavorTextEntry.Replace(System.Environment.NewLine, "");
        }
	}
}
