// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using PokeAppiOS.Views.PokemonDetail.Cells;
using UIKit;

namespace PokeAppiOS.Views
{
	public partial class PokemonEvolutionViewController : UIViewController
	{
        List<string> testData = new List<string>{"bulbasaur2fdasfdsafdsafdsafdsafdsafadsfadsfadsfadsfadsfasdfadsfadsfasdfasdfadsfasdfasdfads%bulbasaur2%bulbasaur3", "bulbasaur1%bulbasaur2%bulbasaur3", "bulbasaur1%bulbasaur2%bulbasaur3",
            "bulbasaur1%bulbasaur2%bulbasaur3", "bulbasaur1%bulbasaur2fdasfdsafdsafdsafdsafdsafadsfadsfadsfadsfadsfasdfadsfadsfasdfasdfadsfasdfasdfads%bulbasaur3", "bulbasaur1%bulbasaur2%bulbasaur3",
            "bulbasaur1%bulbasaur2%bulbasaur3", "bulbasaur1%bulbasaur2%bulbasaur3", "bulbasaur1%bulbasaur2%bulbasaur3", "bulbasaur1%bulbasaur2%bulbasaur3" };

		public PokemonEvolutionViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            pokemonEvolutionChainTableView.RegisterNibForCellReuse(EvolutionVariantTableViewCell.Nib, "EvolutionVariantTableViewCell");
            pokemonEvolutionChainTableView.DataSource = new PokemonEvolutionViewControllerDataSource(this);

        }

        class PokemonEvolutionViewControllerDataSource : UITableViewDataSource
        {
            PokemonEvolutionViewController viewController;

            public PokemonEvolutionViewControllerDataSource(PokemonEvolutionViewController viewController)
            {
                this.viewController = viewController;
            }

            public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
            {
                EvolutionVariantTableViewCell cell = (EvolutionVariantTableViewCell)tableView.DequeueReusableCell("EvolutionVariantTableViewCell");
                var data = viewController.testData[indexPath.Row];
                string[] dataArray = data.Split("%");
                cell.EvolutionChain = dataArray;
                return cell;
            }

            public override nint RowsInSection(UITableView tableView, nint section)
            {
                return 10;
            }
        }
    }
}
