// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PokeAppiOS.Views
{
	public partial class PokemonBaseInfoViewController : UIViewController
	{
		public PokemonBaseInfoViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
